version: '2'
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - 'resin-data:/data'
    command: "gunicorn 'server:app' -b 0.0.0.0:8000"

  worker:
    build: . 
    command: "python worker.py" 
    volumes:
      - 'resin-data:/data'

volumes:
    resin-data:
