version: '2'
services:
  web:
    build: .
    ports:
      - "80:8080"
    volumes:
      - 'resin-data:/data'
    command: "gunicorn 'server:app' -b 0.0.0.0:8080"
    env_file: .env
  worker:
    build: . 
    command: "bash ./start.sh" 
    env_file: .env
    volumes:
      - 'resin-data:/data'

volumes:
    resin-data:
