# fly.toml file generated for crowdfactor on 2022-11-02T15:34:39-06:00

app = "crowdfactor"

kill_signal = "SIGINT"
kill_timeout = 5

[processes]
web = "gunicorn 'lib/app:app' -b 0.0.0.0:8080"
cron = "cron -f"

[env]
SURFLINE_URL = "https://www.surfline.com/surf-report/venice-breakwater/590927576a2e4300134fbed8?camId=5834a1b6e411dc743a5d52f3"
DB_URL = "/mnt/db/crowdfactor.sqlite"

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
http_checks = []
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[mounts]
source = "db"
destination = "/mnt/db"
